version: '3.8'

services:
  app:
    build:
      context: ./service
      dockerfile: Dockerfile
    container_name: fastapi
    volumes:
      - ./service/:/service/
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"